// <auto-generated />
using System;
using ApplicationDotnetAssignment1.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationDotnetAssignment1.Migrations
{
    [DbContext(typeof(HospitalSystemContext))]
    [Migration("20240729131317_FinishAddingData")]
    partial class FinishAddingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 30000,
                            Address = "21 Test Test Drive Sydney NSW",
                            Email = "David@Test.com",
                            Name = "David Sorrell",
                            Password = "123",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30001,
                            Address = "22 Test Test Drive Sydney NSW",
                            Email = "Person@Test.com",
                            Name = "David Person",
                            Password = "Person",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30002,
                            Address = "23 Test Test Drive Sydney NSW",
                            Email = "Rubio@gmail2.com",
                            Name = "Norma Rubio",
                            Password = "FInTheChat",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30003,
                            Address = "24 Test Test Drive Sydney NSW",
                            Email = "Ifan@gmail2.com",
                            Name = "Ifan Norton",
                            Password = "NortonAntiVirus",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30004,
                            Address = "25 Test Test Drive Sydney NSW",
                            Email = "Shaw@gmail2.com",
                            Name = "Sapphire Shaw",
                            Password = "GrimShaw",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30005,
                            Address = "26 Test Test Drive Sydney NSW",
                            Email = "Rick@gmail2.com",
                            Name = "Rick Sanchez",
                            Password = "IAmARickAndMortyReference",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30006,
                            Address = "27 Test Test Drive Sydney NSW",
                            Email = "Mcclain@gmail2.com",
                            Name = "Eleanor Mcclain",
                            Password = "McclainIsTheName",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30007,
                            Address = "28 Test Test Drive Sydney NSW",
                            Email = "Grace@gmail2.com",
                            Name = "Grace O'Connor",
                            Password = "GraceExists",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30008,
                            Address = "29 Test Test Drive Sydney NSW",
                            Email = "Ward@gmail2.com",
                            Name = "Evie Ward",
                            Password = "HospitalWard",
                            PhoneNumber = "0491570110"
                        },
                        new
                        {
                            Id = 30009,
                            Address = "30 Test Test Drive Sydney NSW",
                            Email = "Stokes@gmail2.com",
                            Name = "Lorraine Stokes",
                            Password = "StokesExists",
                            PhoneNumber = "0491570110"
                        });
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            Description = "Cold",
                            DoctorId = 10000,
                            PatientId = 20000
                        },
                        new
                        {
                            Id = 10001,
                            Description = "Something I swear",
                            DoctorId = 10000,
                            PatientId = 20000
                        },
                        new
                        {
                            Id = 10002,
                            Description = "Covid-19",
                            DoctorId = 10002,
                            PatientId = 20002
                        },
                        new
                        {
                            Id = 10003,
                            Description = "A cough",
                            DoctorId = 10002,
                            PatientId = 20002
                        },
                        new
                        {
                            Id = 10004,
                            Description = "Just because",
                            DoctorId = 10004,
                            PatientId = 20004
                        },
                        new
                        {
                            Id = 10005,
                            Description = "Wanted Email",
                            DoctorId = 10004,
                            PatientId = 20004
                        },
                        new
                        {
                            Id = 10006,
                            Description = "I was lonely",
                            DoctorId = 10006,
                            PatientId = 20006
                        },
                        new
                        {
                            Id = 10007,
                            Description = "Dying",
                            DoctorId = 10006,
                            PatientId = 20006
                        },
                        new
                        {
                            Id = 10008,
                            Description = "yearly checkup",
                            DoctorId = 10008,
                            PatientId = 20008
                        },
                        new
                        {
                            Id = 10009,
                            Description = "Because Why not",
                            DoctorId = 10008,
                            PatientId = 20008
                        });
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 10000,
                            Address = "12 Ultimo Road Sydney NSW",
                            Email = "Test@email.com",
                            Name = "John Deer",
                            Password = "test",
                            PhoneNumber = "0491570156"
                        },
                        new
                        {
                            Id = 10001,
                            Address = "10 Ultimo Road Sydney NSW",
                            Email = "Doctor@snaimail.com",
                            Name = "Mr Doctor",
                            Password = "Password",
                            PhoneNumber = "0491570158"
                        },
                        new
                        {
                            Id = 10002,
                            Address = "12 Place Street Sydney NSW",
                            Email = "Jack@PigeonMail.com",
                            Name = "Jack Doe",
                            Password = "hello",
                            PhoneNumber = "0491570151"
                        },
                        new
                        {
                            Id = 10003,
                            Address = "14 100% Real Street Sydney NSW",
                            Email = "Jane@fakegmail.com",
                            Name = "Jane Dane",
                            Password = "123Jane",
                            PhoneNumber = "0491570152"
                        },
                        new
                        {
                            Id = 10004,
                            Address = "100 Place Street Sydney NSW",
                            Email = "Jack@PigeonSnailMail.com",
                            Name = "Jack Test",
                            Password = "JackTest",
                            PhoneNumber = "0491570153"
                        },
                        new
                        {
                            Id = 10005,
                            Address = "2 Somewhere Street Sydney NSW",
                            Email = "Florence@PigeonMail.com",
                            Name = "Florence Padilla",
                            Password = "hellohello",
                            PhoneNumber = "0491570154"
                        },
                        new
                        {
                            Id = 10006,
                            Address = "10 A Real Street Sydney NSW",
                            Email = "Jordan@PigeonMail.com",
                            Name = "Riya Jordan",
                            Password = "JordanRules",
                            PhoneNumber = "0491570155"
                        },
                        new
                        {
                            Id = 10007,
                            Address = "13 Place Street Sydney NSW",
                            Email = "Dan@PigeonMail.com",
                            Name = "Dan Peters",
                            Password = "DanSaysHello",
                            PhoneNumber = "0491570156"
                        },
                        new
                        {
                            Id = 10008,
                            Address = "14 Place Street Sydney NSW",
                            Email = "Church@PigeonMail.com",
                            Name = "Jazmine Church",
                            Password = "JazmineJazmine",
                            PhoneNumber = "0491570157"
                        },
                        new
                        {
                            Id = 10009,
                            Address = "15 Place Street Sydney NSW",
                            Email = "Victoria@PigeonMail.com",
                            Name = "Victoria Mckee",
                            Password = "Mckee",
                            PhoneNumber = "0491570158"
                        });
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("AssignedDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 20000,
                            Address = "10 Street Street Sydney NSW",
                            AssignedDoctorId = 10000,
                            Email = "Test@email.com",
                            Name = "Jill Deer",
                            Password = "DeerIsMyName",
                            PhoneNumber = "0491570157"
                        },
                        new
                        {
                            Id = 20001,
                            Address = "11 Real Street Melbourne VIC",
                            Email = "Test@email.com",
                            Name = "Jane Deer",
                            Password = "Anonymous",
                            PhoneNumber = "0491570006"
                        },
                        new
                        {
                            Id = 20002,
                            Address = "10 Nowhere Drive Sydney NSW",
                            AssignedDoctorId = 10002,
                            Email = "Test@email.com",
                            Name = "Person Person",
                            Password = "Person",
                            PhoneNumber = "0491570158"
                        },
                        new
                        {
                            Id = 20003,
                            Address = "11 Street Street Sydney NSW",
                            Email = "david2017au@gmail.com",
                            Name = "David Sorrell",
                            Password = "MyRealPassword",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20004,
                            Address = "12 Street Street Sydney NSW",
                            AssignedDoctorId = 10004,
                            Email = "Goodwin@gmail2.com",
                            Name = "Vinnie Goodwin",
                            Password = "VinnieIsGood",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20005,
                            Address = "13 Street Street Sydney NSW",
                            Email = "Walls@gmail2.com",
                            Name = "Subhan Walls",
                            Password = "WallsRule",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20006,
                            Address = "14 Street Street Sydney NSW",
                            AssignedDoctorId = 10006,
                            Email = "Sears@gmail2.com",
                            Name = "Lillie Sears",
                            Password = "Sears",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20007,
                            Address = "15 Street Street Sydney NSW",
                            Email = "Clay@gmail2.com",
                            Name = "Connie Clay",
                            Password = "ClayIsTasty",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20008,
                            Address = "16 Street Street Sydney NSW",
                            AssignedDoctorId = 10008,
                            Email = "Diana@gmail2.com",
                            Name = "Diana Petty",
                            Password = "Petty",
                            PhoneNumber = "0491570159"
                        },
                        new
                        {
                            Id = 20009,
                            Address = "17 Street Street Sydney NSW",
                            Email = "Santana@gmail2.com",
                            Name = "Sam Santana",
                            Password = "InspectorSam",
                            PhoneNumber = "0491570159"
                        });
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Appointment", b =>
                {
                    b.HasOne("ApplicationDotnetAssignment1.Models.Doctor", "Doctor")
                        .WithMany("AssignedAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationDotnetAssignment1.Models.Patient", "Patient")
                        .WithMany("BookedAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Patient", b =>
                {
                    b.HasOne("ApplicationDotnetAssignment1.Models.Doctor", "AssignedDoctor")
                        .WithMany("Patients")
                        .HasForeignKey("AssignedDoctorId");

                    b.Navigation("AssignedDoctor");
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Doctor", b =>
                {
                    b.Navigation("AssignedAppointments");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ApplicationDotnetAssignment1.Models.Patient", b =>
                {
                    b.Navigation("BookedAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
